[tool.pdm]
distribution = true

[tool.pdm.dev-dependencies]
dev = [
    "pytest",
    "jupyter",
    "matplotlib",
    "pandas",
    "scikit-learn",
]

[tool.pdm.build]
includes = ["q_alchemy"]
[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"


[project]
name = "q-alchemy-sdk-py"
version = "0.2.0"
description = ""
authors = [
    {name = "Carsten Blank", email = "blank@data-cybernetics.com"},
]
dependencies = [
    "datacybernetics-job-management-hypermedia-client @ file:///${PROJECT_ROOT}/build/datacybernetics_job_management_hypermedia_client-0.2.0.2024.319.1-py3-none-any.whl",
    "qiskit>=1.0.2",
]
requires-python = "<4,>=3.11"
readme = "README.md"
license = {text = "Apache"}

