[tool.poetry]
name = "q-alchemy-sdk-py"
version = "0.1.0"
description = ""
authors = ["Carsten Blank <blank@data-cybernetics.com>"]
readme = "README.md"
packages = [{include = "q_alchemy"}]

[tool.poetry.dependencies]
python = ">=3.9,<4"
numpy = "*"
pyarrow = "*"
requests = "*"
pydantic = "<2"
python-dateutil = "*"
retry = "*"
qiskit_aer = "*"
qclib = "*"

[tool.poetry.dev-dependencies]
pytest = "*"
jupyter = "*"
matplotlib = "*"
pandas = "*"
scikit-learn = "*"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
